CREATE DATABASE IF NOT EXISTS sistema_abc_upbp2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sistema_abc_upbp2;

CREATE TABLE procesos (id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(150) NOT NULL,encargado VARCHAR(150),orden_proceso INT DEFAULT 1);
CREATE TABLE meses (id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(30) NOT NULL,ventas_historicas DECIMAL(15,2) DEFAULT 0,produccion_historica DECIMAL(15,2) DEFAULT 0,ventas_pronosticadas DECIMAL(15,2) DEFAULT 0,inventario_inicial_primer_mes DECIMAL(15,2) DEFAULT 0);
CREATE TABLE inventario_deseado (id INT AUTO_INCREMENT PRIMARY KEY,mes_id INT NOT NULL,inventario_final_deseado DECIMAL(15,2) DEFAULT 0,FOREIGN KEY(mes_id) REFERENCES meses(id) ON DELETE CASCADE);
CREATE TABLE cif_items (id INT AUTO_INCREMENT PRIMARY KEY,mes_id INT NOT NULL,item VARCHAR(150) NOT NULL,costo_fijo DECIMAL(15,2) DEFAULT 0,tasa_variable DECIMAL(15,8) DEFAULT 0,FOREIGN KEY(mes_id) REFERENCES meses(id) ON DELETE CASCADE);
CREATE TABLE pools (id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(150) NOT NULL);
CREATE TABLE pool_procesos (pool_id INT NOT NULL,proceso_id INT NOT NULL,horas DECIMAL(15,4) DEFAULT 0,PRIMARY KEY(pool_id,proceso_id),FOREIGN KEY(pool_id) REFERENCES pools(id) ON DELETE CASCADE,FOREIGN KEY(proceso_id) REFERENCES procesos(id) ON DELETE CASCADE);
CREATE TABLE pool_cif (pool_id INT NOT NULL,cif_id INT NOT NULL,PRIMARY KEY(pool_id,cif_id),FOREIGN KEY(pool_id) REFERENCES pools(id) ON DELETE CASCADE,FOREIGN KEY(cif_id) REFERENCES cif_items(id) ON DELETE CASCADE);
